# Generated by Django 4.1.7 on 2023-06-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_customer_order_orderitem_product_shippingaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('accessory', 'Accessory'), ('decoration', 'Decoration'), ('furniture', 'Furniture')], default='accessory', max_length=20),
            preserve_default=False,
        ),
    ]
