# Generated by Django 4.1.7 on 2023-06-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Man', 'Man'), ('Women', 'Women'), ('Kids', 'Kids')], max_length=20),
        ),
    ]
