# Generated by Django 4.1.7 on 2023-03-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
