# Generated by Django 4.1.7 on 2023-03-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_teste_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
