# Generated by Django 4.1.7 on 2023-03-26 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_teste_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
