# Generated by Django 4.1.7 on 2023-03-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_female_male'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='male',
            name='girls',
        ),
        migrations.DeleteModel(
            name='Female',
        ),
        migrations.DeleteModel(
            name='Male',
        ),
    ]
